' <auto-generated />
Imports System.CodeDom.Compiler
Imports System.Data.Entity.Migrations
Imports System.Data.Entity.Migrations.Infrastructure
Imports System.Resources

Namespace Migrations
    <GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")>
    Public NotInheritable Partial Class Add_Table_AspNetUserActionSousRessource_To_Know_Witch_User_Can_Make_Witch_Action
        Implements IMigrationMetadata
    
        Private ReadOnly Resources As New ResourceManager(GetType(Add_Table_AspNetUserActionSousRessource_To_Know_Witch_User_Can_Make_Witch_Action))
        
        Private ReadOnly Property IMigrationMetadata_Id() As String Implements IMigrationMetadata.Id
            Get
                Return "202004031258513_Add_Table_AspNetUserActionSousRessource_To_Know_Witch_User_Can_Make_Witch_Action"
            End Get
        End Property
        
        Private ReadOnly Property IMigrationMetadata_Source() As String Implements IMigrationMetadata.Source
            Get
                Return Nothing
            End Get
        End Property
        
        Private ReadOnly Property IMigrationMetadata_Target() As String Implements IMigrationMetadata.Target
            Get
                Return Resources.GetString("Target")
            End Get
        End Property
    End Class
End Namespace
