' <auto-generated />
Imports System.CodeDom.Compiler
Imports System.Data.Entity.Migrations
Imports System.Data.Entity.Migrations.Infrastructure
Imports System.Resources

Namespace Migrations
    <GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")>
    Public NotInheritable Partial Class Alter_Table_ValeurChamps_Add_Fields_CodeCollecte_DateSynchro_DateCollecte_StatutExist_Latitude_Longitude
        Implements IMigrationMetadata
    
        Private ReadOnly Resources As New ResourceManager(GetType(Alter_Table_ValeurChamps_Add_Fields_CodeCollecte_DateSynchro_DateCollecte_StatutExist_Latitude_Longitude))
        
        Private ReadOnly Property IMigrationMetadata_Id() As String Implements IMigrationMetadata.Id
            Get
                Return "202107081122156_Alter_Table_ValeurChamps_Add_Fields_CodeCollecte_DateSynchro_DateCollecte_StatutExist_Latitude_Longitude"
            End Get
        End Property
        
        Private ReadOnly Property IMigrationMetadata_Source() As String Implements IMigrationMetadata.Source
            Get
                Return Nothing
            End Get
        End Property
        
        Private ReadOnly Property IMigrationMetadata_Target() As String Implements IMigrationMetadata.Target
            Get
                Return Resources.GetString("Target")
            End Get
        End Property
    End Class
End Namespace
